### ISSUE TITLE
Provide link to Javadoc documentation?

### ISSUE THREAD

**Issue by FranklinChen** [colindean/keepachangelog-parser-java#1]
Generate Javadoc for the API and provide a link to it?

**Comment by colindean** [comment]
Looks like this can be done easily through https://www.javadoc.io/ if the package is in Maven Central (#2).

**Comment by colindean** [comment]
I got Maven Central deployment working but I think Javadoc.io is 24 hours behind.

When it's available, it'll be at https://javadoc.io/doc/cx.cad.keepachangelog/changelog-parser.

I'll keep this open to verify it tomorrow evening.

**Comment by colindean** [comment]
I went on a tab cleaning spree and checked. It's live.

https://javadoc.io/doc/cx.cad.keepachangelog/changelog-parser/0.1.3

**Comment by FranklinChen** [comment]
Nice. Thanks.
