### ISSUE TITLE
Thanks!  I used your library to build something

### ISSUE THREAD

**Issue by nedtwigg** [colindean/keepachangelog-parser-java#7]
Hi @colindean!  Just wanted to let you know that I used this library to make a gradle plugin called [spotless-changelog](https://github.com/diffplug/spotless-changelog).  It keeps the changelog formatted, and then uses the content of the `[Unreleased]` block to compute the next version.  In the end, I replaced the functionality in keepachangelog-parser-java with something [less powerful](https://javadoc.io/static/com.diffplug.spotless-changelog/spotless-changelog-lib/1.0.0/com/diffplug/spotless/changelog/Changelog.html), so I'm not actually using this library anymore.  But spotless-changelog has been very helpful to me while I've been using it, and I never would have tried to build it if this didn't exist already.  So thanks!

**Comment by nedtwigg** [comment]
Btw I plugged this library at the bottom of the README, lemme know if you'd like any changes.

**Comment by colindean** [comment]
Thank you for your kind words. I'm glad my work was inspirational. My intent had been to eventually produce a Gradle plugin, so I'm glad that someone took that on!
